import {useMemo,useState} from 'react';import type {FormData} from './types/questionnaire';import {directions,productionOptions,techSkills} from './data/questionnaire';
const emptyRatings=(items:readonly (readonly [string,string])[])=>Object.fromEntries(items.map(([k])=>[k,null]));
const initial:FormData={fullName:'',projectTeam:'',commercialExperience:'',technicalBackground:emptyRatings(techSkills),tasksOutsideFrontend:'',productionExperience:[],productionExperienceOther:'',productionExamples:'',developmentInterest:emptyRatings(directions),priorityDirections:[],threeMonthDirection:'',threeMonthDirectionReason:'',desiredIndependentTasks:'',pilotParticipation:'',learningTimePerWeek:'',knowledgeSharing:'',learningObstacles:''};
function App(){const [f,setF]=useState<FormData>(initial);const [show,setShow]=useState(false);const [error,setError]=useState(false);const set=(k:keyof FormData,v:any)=>setF(x=>({...x,[k]:v}));
const valid=useMemo(()=>!!(f.fullName.trim()&&f.projectTeam.trim()&&f.commercialExperience&&Object.values(f.technicalBackground).every(v=>v!==null)&&f.tasksOutsideFrontend.trim()&&f.productionExperience.length&&(!f.productionExperience.includes('other')||f.productionExperienceOther.trim())&&f.productionExamples.trim()&&Object.values(f.developmentInterest).every(v=>v!==null)&&f.priorityDirections.length&&f.threeMonthDirection&&f.threeMonthDirectionReason.trim()&&f.desiredIndependentTasks.trim()&&f.pilotParticipation&&f.learningTimePerWeek&&f.knowledgeSharing&&f.learningObstacles.trim()),[f]);
const result={questionnaireId:'developer-survey-v1',questionnaireVersion:1,completedAt:new Date().toISOString(),answers:f};const submit=()=>{if(!valid){setError(true);document.querySelector('.invalid')?.scrollIntoView({behavior:'smooth',block:'center'});return}setError(false);setShow(true)};
return <main><header><h1>Анкета разработчика</h1><p>Опыт, интересы и готовность к развитию</p></header>
<Section title="Блок 1. Общая информация"><Text q="1. ФИО" value={f.fullName} onChange={v=>set('fullName',v)} bad={error&&!f.fullName.trim()}/><Text q="2. Текущий проект / команда" value={f.projectTeam} onChange={v=>set('projectTeam',v)} bad={error&&!f.projectTeam.trim()}/><Radio q="3. Общий опыт коммерческой разработки" options={[['lt1','< 1 года'],['1-2','1–2 года'],['3-5','3–5 лет'],['5plus','5+ лет']]} value={f.commercialExperience} onChange={v=>set('commercialExperience',v)} bad={error&&!f.commercialExperience}/></Section>
<Section title="Блок 2. Текущий технический бэкграунд"><p className="hint">0 — нет опыта; 1 — знаком с основами; 2 — выполнял отдельные задачи; 3 — могу самостоятельно выполнять рабочие задачи; 4 — могу консультировать/менторить других.</p>{techSkills.map(([k,l])=><Rating key={k} label={l} max={4} value={f.technicalBackground[k]} onChange={v=>setF(x=>({...x,technicalBackground:{...x.technicalBackground,[k]:v}}))} bad={error&&f.technicalBackground[k]===null}/>)}</Section>
<Section title="Блок 3. Практический опыт"><Text area q="4. Какие задачи за пределами классического фронтенда ты уже выполнял?" value={f.tasksOutsideFrontend} onChange={v=>set('tasksOutsideFrontend',v)} bad={error&&!f.tasksOutsideFrontend.trim()}/><Checks q="5. По каким смежным направлениям у тебя был реальный production-опыт?" options={productionOptions} value={f.productionExperience} onChange={v=>set('productionExperience',v)} bad={error&&!f.productionExperience.length}/>{f.productionExperience.includes('other')&&<Text q="Уточни вариант «Другое»" value={f.productionExperienceOther} onChange={v=>set('productionExperienceOther',v)} bad={error&&!f.productionExperienceOther.trim()}/>}<Text area q="6. Приведи 1–3 примера таких задач. Что именно ты делал самостоятельно?" value={f.productionExamples} onChange={v=>set('productionExamples',v)} bad={error&&!f.productionExamples.trim()}/></Section>
<Section title="Блок 4. Куда хочется развиваться"><p className="question">7. Насколько тебе интересно развиваться в каждом направлении?</p><p className="hint">1 — совсем не интересно; 5 — очень хочу развиваться.</p>{directions.map(([k,l])=><Rating key={k} label={l} min={1} max={5} value={f.developmentInterest[k]} onChange={v=>setF(x=>({...x,developmentInterest:{...x.developmentInterest,[k]:v}}))} bad={error&&f.developmentInterest[k]===null}/>)}<Checks q="8. Выбери до 3 направлений, которые хотел бы изучать в первую очередь." options={directions} value={f.priorityDirections} max={3} onChange={v=>set('priorityDirections',v)} bad={error&&!f.priorityDirections.length}/><Radio q="9. Если можно выбрать только одно направление на ближайшие 3 месяца, что выберешь?" options={directions} value={f.threeMonthDirection} onChange={v=>set('threeMonthDirection',v)} bad={error&&!f.threeMonthDirection}/><Text area q="10. Почему именно его?" value={f.threeMonthDirectionReason} onChange={v=>set('threeMonthDirectionReason',v)} bad={error&&!f.threeMonthDirectionReason.trim()}/><Text area q="11. Какие конкретные задачи ты хотел бы научиться решать самостоятельно?" value={f.desiredIndependentTasks} onChange={v=>set('desiredIndependentTasks',v)} bad={error&&!f.desiredIndependentTasks.trim()}/></Section>
<Section title="Блок 5. Мотивация и участие в пилоте"><Radio q="12. Готов ли ты участвовать в пилотной программе обучения длительностью около 1–3 месяцев параллельно с проектной работой?" options={[['yes','Да'],['ratherYes','Скорее да'],['ratherNo','Скорее нет'],['no','Нет']]} value={f.pilotParticipation} onChange={v=>set('pilotParticipation',v)} bad={error&&!f.pilotParticipation}/><Radio q="13. Сколько времени в неделю ты реально готов выделять на обучение?" options={[['1-2','1–2 часа'],['3-4','3–4 часа'],['5-8','5–8 часов'],['8plus','8+ часов']]} value={f.learningTimePerWeek} onChange={v=>set('learningTimePerWeek',v)} bad={error&&!f.learningTimePerWeek}/><Radio q="14. Готов ли после обучения делиться знаниями с командой / проводить внутренние разборы / помогать коллегам?" options={[['yes','Да'],['maybe','Возможно'],['no','Нет']]} value={f.knowledgeSharing} onChange={v=>set('knowledgeSharing',v)} bad={error&&!f.knowledgeSharing}/><Text area q="15. Что может помешать тебе пройти обучение?" value={f.learningObstacles} onChange={v=>set('learningObstacles',v)} bad={error&&!f.learningObstacles.trim()}/></Section>
<button className="result" onClick={submit}>Результат</button>{error&&!valid&&<p className="errorSummary">Заполните все обязательные поля.</p>}{show&&<div className="resultBox"><h2>Результат анкеты</h2><pre>{JSON.stringify(result,null,2)}</pre><div className="actions"><button onClick={()=>navigator.clipboard.writeText(JSON.stringify(result,null,2))}>Скопировать JSON</button><button onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));a.download=`developer-survey-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}}>Скачать JSON</button></div></div>}</main>}
function Section({title,children}:{title:string,children:any}){return <section><h2>{title}</h2>{children}</section>}
function Text({q,value,onChange,area,bad}:{q:string,value:string,onChange:(v:string)=>void,area?:boolean,bad?:boolean}){return <div className={`field ${bad?'invalid':''}`}><label>{q}</label>{area?<textarea value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>} {bad&&<small>Заполните поле</small>}</div>}
function Radio({q,options,value,onChange,bad}:{q:string,options:readonly (readonly [string,string])[],value:string,onChange:(v:string)=>void,bad?:boolean}){return <div className={`field ${bad?'invalid':''}`}><p className="question">{q}</p><div className="choices">{options.map(([v,l])=><label key={v}><input type="radio" checked={value===v} onChange={()=>onChange(v)}/>{l}</label>)}</div>{bad&&<small>Заполните поле</small>}</div>}
function Checks({q,options,value,onChange,max,bad}:{q:string,options:readonly (readonly [string,string])[],value:string[],onChange:(v:string[])=>void,max?:number,bad?:boolean}){return <div className={`field ${bad?'invalid':''}`}><p className="question">{q}</p><div className="choices">{options.map(([v,l])=>{const checked=value.includes(v),disabled=!!max&&!checked&&value.length>=max;return <label key={v} className={disabled?'disabled':''}><input type="checkbox" checked={checked} disabled={disabled} onChange={()=>onChange(checked?value.filter(x=>x!==v):[...value,v])}/>{l}</label>})}</div>{bad&&<small>Заполните поле</small>}</div>}
function Rating({label,value,onChange,max,min=0,bad}:{label:string,value:number|null,onChange:(v:number)=>void,max:number,min?:number,bad?:boolean}){return <div className={`rating ${bad?'invalid':''}`}><span>{label}</span><div>{Array.from({length:max-min+1},(_,i)=>i+min).map(n=><button type="button" key={n} className={value===n?'selected':''} onClick={()=>onChange(n)}>{n}</button>)}</div></div>}
export default App;
